from . import f_res_settings_inherit
from . import f_vendor_contact_person
from . import f_res_partner_inherit
from . import f_res_country_inherit
from . import f_classification
from . import f_classification_approval
from . import f_bill_of_loading_type
from . import f_account_incoterm_inherit
from . import f_account_move_inherit
from . import f_purchase_order_lockups
from . import f_shipping_dates_history
from . import f_shipping_details
from . import f_purchase_order_inherit
from . import f_container_plans
from . import f_container_details
from . import f_purchase_order_planning
from . import f_res_users_inherit
from . import f_product_template_inherit
